[main]
position=top
orientation=h
width=300
height=50
icon-size=26
show-percentage=true
margins=0 0 0 0
timeout=1
transition-time=200
listeners=audio_in,audio_out,backlight
backlight-path=
keyboard-backlight-path=
keyboard-path=
